# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-23 11:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bidding_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidding',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
