# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-19 15:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20200523_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bids',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
