# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('mens', 'mens'), ('womens', 'womens')], default='mens', max_length=50)),
                ('clothingType', models.CharField(choices=[('tops', 'tops'), ('shirts', 'shirts'), ('jumpers', 'jumpers'), ('jeans', 'jeans'), ('accessories', 'accessories')], default='', max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
