# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_buyout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clothingType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='auctionTimer',
            field=models.DateTimeField(null=True),
        ),
    ]
