# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-19 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200807_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='largeDescription',
        ),
        migrations.AddField(
            model_name='product',
            name='highestBidder',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
